services:
  mysql:
    image: mysql:8.0
    container_name: noah_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webstore
      MYSQL_USER: noah_user
      MYSQL_PASSWORD: noah_password
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:15
    container_name: noah_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: finance
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: noah_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  order_api:
    build: ./module_4/order_api
    container_name: noah_order_api
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: noah_user
      DB_PASSWORD: noah_password
      DB_NAME: webstore
    expose:
      - "5000"
    depends_on:
      mysql:
        condition: service_healthy

  report-service:
    build: ./module_4/report_service
    container_name: noah-report-service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: noah_user
      DB_PASSWORD: noah_password
      DB_NAME: webstore
    expose:
      - "5001"
    depends_on:
      mysql:
        condition: service_healthy

  kong:
    image: kong:latest
    container_name: noah_kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: "off"
    ports:
      - "8000:8000"
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:ro
    depends_on:
      - order_api
      - report-service

volumes:
  mysql_data:
